pipeline {
    // 対象ノードの指定
    agent {
        label '1017918_build1008017'
    }
    environment {
        JAVA_HOME = "/opt/java/openjdk-8u232-b09"
        MAVEN_HOME = "/opt/tools/apache-maven-3.6.3"

    }

    stages {
        stage('Preparation') {
            steps {
                deleteDir()
                sh "mkdir report"
                sh "mkdir last_src"
                sh "mkdir init_src"


                //gitやsvnからソースを取得する。
                dir('last_src'){
                    // 最新ソースをscmからソースを取得する。
                    git branch: 'master', credentialsId: '324a7621-1ef1-493a-a3a4-b85df6094307', url: 'https://sfdjp11087.swf.nec.co.jp/gitlab/swf_sample_project/swf_linux_java.git'
                }
                // ncmeter による測定を実行する。
                sh "/opt/tools/ncmeter/bin/ncmeter -diff -v -F xml -RESTYLE NONE init_src/ last_src/src/main -Tfp last_src/ncmeter.properties -Tfo report/ncmeter-diff.xml"
                sh "/opt/tools/ncmeter/bin/ncmeter -struct -v -F xml last_src/src/main -Tfp last_src/ncmeter.properties -Tfo report/ncmeter-struct.xml"
            }
        }
        stage('build') {
            // ビルドおよびテスト実行。
            steps {
                dir('last_src') {
                    sh '''
                        ${MAVEN_HOME}/bin/mvn clean package
                    '''
                }
            }
        }
        stage('Report') {
            // SonarQubeの解析実行
            steps {
                dir('last_src'){
                    //bat "call ${MAVEN_HOME}\\bin\\mvn.cmd org.jacoco:jacoco-maven-plugin:report"
                    // SonarQube Scannerを実行する。
                    withSonarQubeEnv("a1017918jnk@swf.nec.co.jp") {
                        sh "/opt/tools/sonar-scanner/bin/sonar-scanner"
                    }
                }
            }
        }
        stage ('Archive') {
            steps {
                archiveArtifacts '**/target/*.jar'
            }
        }
    }
}
